apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-graf-k8s-app 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-graf-k8s-app
  template:
    metadata:
      labels:
        app: prom-graf-k8s-app
    spec:
      containers:
      - name: prom-graf-k8s-app
        image: prom-graf-k8s-app:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
--- 
apiVersion: v1
kind: Service 
metadata:
  name: prom-graf-k8s-app
spec:
  selector:
    app: prom-graf-k8s-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
